name: simgen
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_metadata=8.7.0=h40b2b14_1
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - ld_impl_linux-64=2.40=h12ee557_0
  - libdrm-conda-x86_64=2.4.97=ha134caf_1109
  - libdrm-cos7-x86_64=2.4.97=ha675448_1106
  - libegl=1.7.0=ha4b6fd6_2
  - libegl-devel=1.7.0=ha4b6fd6_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgl=1.7.0=ha4b6fd6_2
  - libgl-devel=1.7.0=ha4b6fd6_2
  - libglu=9.0.0=he1b5a44_1001
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libglx-devel=1.7.0=ha4b6fd6_2
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - mesa-khr-devel-cos7-x86_64=18.3.4=ha675448_1106
  - mesa-libegl-conda-x86_64=18.3.4=ha134caf_1109
  - mesa-libegl-cos7-x86_64=18.3.4=ha675448_1106
  - mesa-libegl-devel-cos7-x86_64=18.3.4=ha675448_1106
  - mesa-libgbm-conda-x86_64=18.3.4=ha134caf_1109
  - mesa-libgbm-cos7-x86_64=18.3.4=ha675448_1106
  - mesa-libglapi-conda-x86_64=18.3.4=ha134caf_1109
  - mesa-libglapi-cos7-x86_64=18.3.4=ha675448_1106
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.17=h5eee18b_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - setuptools=78.1.1=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - sysroot_linux-64=2.17=h57e8cba_10
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiobotocore==2.24.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aioitertools==0.12.0
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anthropic==0.65.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attr==0.3.2
      - attrs==25.4.0
      - av==16.0.1
      - blinker==1.9.0
      - botocore==1.34.51
      - bpy==3.6.0
      - cattrs==25.3.0
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorlog==6.9.0
      - comm==0.2.3
      - compress-json==1.1.1
      - compress-pickle==2.1.0
      - configargparse==1.7.1
      - contourpy==1.3.2
      - convcolors==2.2.0
      - cycler==0.12.1
      - cython==3.1.6
      - daqp==0.7.2
      - dash==3.2.0
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - deprecated==1.2.18
      - diffusers==0.11.1
      - distro==1.9.0
      - editdistance==0.8.1
      - egl-probe==1.0.2
      - einops==0.8.1
      - embreex==2.17.7.post6
      - etils==1.13.0
      - evdev==1.9.2
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - extcolors==1.0.0
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.2
      - filelock==3.19.1
      - flask==3.1.2
      - fonttools==4.59.2
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - ftfy==6.3.1
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - glfw==2.9.0
      - grpcio==1.74.0
      - gymnasium==1.2.0
      - h11==0.16.0
      - h5py==3.14.0
      - hidapi==0.14.0.post4
      - httpcore==1.0.9
      - httpx==0.28.1
      - httpx-sse==0.4.1
      - huggingface-hub==0.23.4
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - inquirerpy==0.3.4
      - iopath==0.1.10
      - ipython==8.37.0
      - ipywidgets==8.1.7
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter-core==5.8.1
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.9
      - kornia==0.7.2
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - libigl==2.6.1
      - lightning-utilities==0.15.2
      - llvmlite==0.44.0
      - loguru==0.7.3
      - lxml==6.0.1
      - manifold3d==3.1.1
      - mapbox-earcut==1.0.3
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.6
      - matplotlib-inline==0.1.7
      - mcp==1.10.1
      - mdurl==0.1.2
      - meshcat==0.3.2
      - mink==0.0.12
      - moviepy==2.2.1
      - mpmath==1.3.0
      - mujoco==3.3.4
      - multidict==6.6.4
      - mypy-extensions==1.1.0
      - nbformat==5.10.4
      - networkx==3.4.2
      - ninja==1.13.0
      - numba==0.61.2
      - numpy==1.26.4
      - nvdiffrast==0.3.3
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-curobo==0.7.7.post1.dev4+dirty
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - omni-isaac-lab==0.30.7
      - omni-isaac-lab-assets==0.1.4
      - omni-isaac-lab-tasks==0.10.18
      - onnx==1.16.1
      - open-clip-torch==2.32.0
      - open3d==0.19.0
      - openai==1.104.1
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.3.2
      - parso==0.8.5
      - pexpect==4.9.0
      - pfzy==0.3.4
      - pillow==9.5.0
      - platformdirs==4.4.0
      - pluggy==1.6.0
      - plyfile==1.1.2
      - prettytable==3.3.0
      - proglog==0.1.12
      - prompt-toolkit==3.0.52
      - propcache==0.3.2
      - protobuf==4.25.8
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybind11==3.0.1
      - pycollada==0.9.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydantic-settings==2.10.1
      - pydeprecate==0.3.1
      - pyglet==1.5.31
      - pygltflib==1.16.5
      - pygments==2.19.2
      - pylette==2.0.1
      - pyngrok==7.3.0
      - pynndescent==0.5.13
      - pynput==1.8.1
      - pyopengl==3.1.10
      - pyopengl-accelerate==3.1.10
      - pyparsing==3.2.3
      - pyperclip==1.9.0
      - pyquaternion==0.9.9
      - pytest==8.4.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - python-xlib==0.33
      - pytorch-lightning==1.4.3
      - pytorch3d==0.7.8
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - pyzmq==27.0.2
      - qpsolvers==4.8.1
      - referencing==0.36.2
      - regex==2025.9.1
      - requests==2.32.5
      - retrying==1.4.2
      - rich==14.1.0
      - robosuite==1.5.1
      - rpds-py==0.27.1
      - rtree==1.4.1
      - s3fs==2025.9.0
      - safetensors==0.6.2
      - sapien==3.0.1
      - scikit-image==0.20.0
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentence-transformers==4.1.0
      - sentry-sdk==2.39.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sse-starlette==3.0.2
      - stack-data==0.6.3
      - starlette==0.47.3
      - svg-path==7.0
      - sympy==1.13.1
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.4
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.19
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.2.1
      - torch==2.5.1+cu124
      - torchaudio==2.5.1+cu124
      - torchmetrics==0.6.0
      - torchvision==0.20.1+cu124
      - tornado==6.5.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.41.2
      - transforms3d==0.4.2
      - trimesh==4.8.1
      - triton==3.1.0
      - typer==0.17.3
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - u-msgpack-python==2.8.0
      - umap-learn==0.5.9.post2
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - vhacdx==0.0.8.post2
      - wandb==0.22.1
      - warp-lang==1.8.1
      - wcwidth==0.2.13
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - wrapt==1.17.3
      - xatlas==0.0.11
      - xxhash==3.5.0
      - yarl==1.20.1
      - yourdfpy==0.0.58
      - zstandard==0.25.0
prefix: /home/hongchix/main/miniconda3/envs/simgen
